"""add_scraped_rent_features_v400

Revision ID: 62939b3d1c0f
Revises: 058d0c64c3ab
Create Date: 2026-03-09 19:42:12.650186

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "62939b3d1c0f"
down_revision: Union[str, None] = "058d0c64c3ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "properties", sa.Column("actual_market_rent_weekly", sa.Float(), nullable=True)
    )
    op.add_column("properties", sa.Column("price_drop_pct", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("properties", "price_drop_pct")
    op.drop_column("properties", "actual_market_rent_weekly")
    # ### end Alembic commands ###
